### PR TITLE
feat: Added Query Acceleration for Warehouses

### PR DESCRIPTION
**Pull request by ChrisIsidora**
Added Query Acceleration for Warehouses. (Currently in Preview)

## References
* https://docs.snowflake.com/en/sql-reference/sql/create-warehouse.html#query-acceleration-properties

### CODE REVIEW

**Comment by sfc-gh-swinkler** [comment]
the test account used for CI/CD is currently set to run in standard, not enterprise. i do have access to an enterprise test account and can switch the credentials to that one. how soon do you need this feature? i see it is a draft, so its not clear the priority

**Comment by ChrisIsidora** [comment]
> the test account used for CI/CD is currently set to run in standard, not enterprise. i do have access to an enterprise test account and can switch the credentials to that one. how soon do you need this feature? i see it is a draft, so its not clear the priority

@sfc-gh-swinkler This is a draft because I was not sure when this will be released for other non enterprise accounts and also for the reason that it's still in public preview. At this moment I does not have as high of a priority as the other PR that you already merged. 

Do you think it;s wise to test en merge it now?

**Comment by marcincuber** [comment]
It would be great to get this merged and released.

**Comment by ChrisIsidora** [comment]
> It would be great to get this merged and released.

@marcincuber I removed it from Draft. @sfc-gh-swinkler Can you check if this doesn't break when these settings are not set and the account is not an Enterprise? Thanks in advance

**Comment by ChrisIsidora** [comment]
@sfc-gh-swinkler  Added docs can you run the tests again? Thanks in advance

**Comment by sfc-gh-swinkler** [comment]
Hey @ChrisIsidora 

getting the following error:

```
> 
> > --- FAIL: TestWarehouseCreate (0.00s)
> >     warehouse_test.go:36: 
> >         	Error Trace:	/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/warehouse_test.go:36
> >         	            				/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/helpers.go:21
> >         	            				/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/warehouse_test.go:32
> >         	Error:      	Received unexpected error:
> >         	            	enable_query_acceleration: '' expected type 'bool', got unconvertible type 'sql.NullBool', value: '{false false}'
> >         	Test:       	TestWarehouseCreate
> > --- FAIL: TestWarehouseRead (0.00s)
> >     warehouse_test.go:58: 
> >         	Error Trace:	/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/warehouse_test.go:58
> >         	            				/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/helpers.go:21
> >         	            				/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/warehouse_test.go:55
> >         	Error:      	Received unexpected error:
> >         	            	enable_query_acceleration: '' expected type 'bool', got unconvertible type 'sql.NullBool', value: '{false false}'
> >         	Test:       	TestWarehouseRead
```

i have had this same problem before all you have to do is `<var>.Bool` to get the correct result. Otherwise looks like everything is good.

**Comment by ChrisIsidora** [comment]
@sfc-gh-swinkler I made the changes I think?

**Comment by sfc-gh-swinkler** [comment]
@ChrisIsidora it is failing on check-docs. Could you please run `make docs`? if that doesn't work then i will just merge and fix it later.

**Comment by ChrisIsidora** [comment]
@sfc-gh-swinkler The docs were already made, I made some changes for the bool property

**Comment by sfc-gh-swinkler** [comment]
hmm well it looks like rebasing to main helped. Getting a new error 
```
--- FAIL: TestWarehouseCreate (0.00s)
    warehouse_test.go:36: 
        	Error Trace:	/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/warehouse_test.go:36
        	            				/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/helpers.go:21
        	            				/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/warehouse_test.go:32
        	Error:      	Received unexpected error:
        	            	query_acceleration_max_scale_factor: '' expected type 'int', got unconvertible type 'sql.NullInt64', value: '{0 false}'
        	Test:       	TestWarehouseCreate
--- FAIL: TestWarehouseRead (0.00s)
    warehouse_test.go:58: 
        	Error Trace:	/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/warehouse_test.go:58
        	            				/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/helpers.go:21
        	            				/home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake/pkg/resources/warehouse_test.go:55
        	Error:      	Received unexpected error:
        	            	query_acceleration_max_scale_factor: '' expected type 'int', got unconvertible type 'sql.NullInt64', value: '{0 false}'
        	Test:       	TestWarehouseRead
FAIL
```

looks like you need to do change the following:

```
	err = d.Set("query_acceleration_max_scale_factor", w.QueryAccelerationMaxScaleFactor)
```
to

```
	err = d.Set("query_acceleration_max_scale_factor", int(w.QueryAccelerationMaxScaleFactor.Int64))
```
or something like that

**Comment by ChrisIsidora** [comment]
@sfc-gh-swinkler Made some changes for the int property

**Review by sfc-gh-swinkler — APPROVED** [review]

**Comment by sfc-gh-swinkler** [comment]
@ChrisIsidora great thanks! I appreciate your contribution.

**Pull request merged**
