### PR TITLE
feat: Add port/protocol for driver

### PR DESCRIPTION
**Pull request by Dirrk**
Adds the ability to provide protocol and port options to the snowflake driver

## Test Plan
* [X] acceptance tests
* [X] Locally we have tested this for almost two weeks

## References
* https://github.com/snowflakedb/gosnowflake/blob/master/dsn.go#L54

### CODE REVIEW

**Comment by Dirrk** [comment]
I rebased the changes in main and made sure the docs were updated properly this time, should be ready for testing

**Comment by alldoami** [comment]
We fixed this test in a different PR, could you merge main into your branch and then we can merge your PR?

**Comment by mrlannigan** [comment]
Hi @alldoami,

I have updated this PR with the latest from main.

**Comment by sfc-gh-swinkler** [comment]
#1238 closes this PR

**Pull request closed without merging**
