### PR TITLE
feat: Support for selecting language in snowflake_procedure

### PR DESCRIPTION
**Pull request by emancu**
Implements https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/948

The previous behaviour was always setting `JAVASCRIPT` as language.
The implementation in this PR breaks the "backwards compatibility" with that rule to honour the Snowflake default: `SQL`.

In addition, documentation for `procedure_grant` and `function_grant` is updated too.

## References

* https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/948
* https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/982

### CODE REVIEW

**Comment by emancu** [comment]
Do I need to do something in particular to get the approval to run the workflows?

**Comment by alldoami** [comment]
Hi! Thank you for being patient! We were fixing some go package updates, we'll take a look at this soon! In the meantime, can you fix the conflicts?

**Comment by emancu** [comment]
@alldoami Done, now the docs should be up to date too.

However, I'm struggling here. The definition of `arguments` for `procedure` is the same as `procedure_grant` and `function_grant`, however, the documentation generated is different!

In fact, the docs generated for `procedure_grant` and `function_grant` is incorrect (https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/982) but I can't figure out how to fix it 😓

**Comment by emancu** [comment]
> Our docs are generated from the resource definition schemas! So for `procedure_grant`, you'll want to modify the descriptions here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/procedure_grant.go, and for `function_grant`, you'll want to modify the descriptions here: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/resources/function_grant.go. Does that make sense?

Yes and no 😅 . The descriptions get updated as expected, but the problem is with the sample code generated.

Running `make checks-docs` generates the following example for `procedure_grant` and `function_grant`

```
arguments   = [
    {
      "name": "a",
      "type": "array"
    },
    {
      "name": "b",
      "type": "string"
    }
  ]
```

However, for `procedure` it generates the following (which in fact it is the correct)

```
  arguments {
    name = "a"
    type = "array"
  }

  arguments {
    name = "b"
    type = "string"
  }
```


ℹ️ The three of them share the same* definition for arguments, which it is

```go
	"arguments": {
		Type: schema.TypeList,
		Elem: &schema.Resource{
			Schema: map[string]*schema.Schema{
				"name": {
					Type:     schema.TypeString,
					Required: true,
					Description:      "The argument name",
				},
				"type": {
					Type:     schema.TypeString,
					Required: true,
					Description:      "The argument type",
				},
			},
		},
		Optional:    true,
		Description: "List of the arguments for the procedure",
		ForceNew:    true,
	},
```
> (*) procedure uses `DiffSuppressFunc: DiffTypes` but it shouldn't affect.



Am I missing something obvious? 🤔

**Comment by alldoami** [comment]
@emancu examples are written here manually :) https://github.com/Snowflake-Labs/terraform-provider-snowflake/tree/main/examples/resources

**Comment by emancu** [comment]
@alldoami Thank you so much!
Docs are updated now 🎉

**Review by sfc-gh-swinkler — APPROVED** [review]

**Pull request merged**
