### PR TITLE
fix: errors package with new linter rules

### PR DESCRIPTION
**Pull request by mnagaa**
This PR adds two linter rules related to error package and syntax.
Also, I fixed a lot of lines to pass the lint rules without editing any test files.

Removed this repo: https://github.com/pkg/errors

### CODE REVIEW

**Comment by mnagaa** [comment]
@sfc-gh-swinkler Hi, could you please review this PR?

**Comment by sfc-gh-swinkler** [comment]
looks good except getting an error:
```
go: updates to go.mod needed; to update it:
	go mod tidy
```
also golang-cilint is failing with:

```
level=info msg="[config_reader] Config search paths: [./ /home/runner/work/terraform-provider-snowflake/terraform-provider-snowflake /home/runner/work/terraform-provider-snowflake /home/runner/work /home/runner /home /]"
level=info msg="[config_reader] Used config file .golangci.yml"
level=info msg="[lintersdb] Active 18 linters: [errcheck errname errorlint exportloopref gocritic godot gofmt gofumpt gosimple govet ineffassign misspell staticcheck thelper typecheck unconvert wastedassign whitespace]"
level=info msg="[loader] Go packages loading at mode [5](https://github.com/Snowflake-Labs/terraform-provider-snowflake/actions/runs/3491308560/jobs/5844655543#step:6:6)75 (deps|name|types_sizes|compiled_files|exports_file|files|imports) took 5[6](https://github.com/Snowflake-Labs/terraform-provider-snowflake/actions/runs/3491308560/jobs/5844655543#step:6:7)3.901834ms"
level=error msg="Running error: context loading failed: no go files to analyze"
level=info msg="Memory: [7](https://github.com/Snowflake-Labs/terraform-provider-snowflake/actions/runs/3491308560/jobs/5844655543#step:6:8) samples, avg is 27.3MB, max is 27.4MB"
level=info msg="Execution took 570.16[8](https://github.com/Snowflake-Labs/terraform-provider-snowflake/actions/runs/3491308560/jobs/5844655543#step:6:9)2ms"
Error: Process completed with exit code 5.
```

**Comment by mnagaa** [comment]
@sfc-gh-swinkler 
Thank you for your feedback! The new commit removes the implementation merged commit in other PR with `github.com/pkg/errors` which has already been in read-only mode (no developing). 
Could you please check this again especially only new commit?🙏

**Comment by mnagaa** [comment]
@sfc-gh-swinkler
Could you please check this? I would like to improve this provider.

**Review by sfc-gh-swinkler — APPROVED** [review]

**Comment by sfc-gh-swinkler** [comment]
@mnagaa thank you for your contribution!

**Pull request merged**
