### PR TITLE
fix: Allow creation of database-wide future external table grants

### PR DESCRIPTION
**Pull request by frederikdesmedt**
Allows user to create future external table grants where the schema is left empty.

## Test Plan
* [x] Unit test to verify that schemas still have to be filled in for non-future grants

## References
Solves #996

### CODE REVIEW

**Comment by alldoami** [comment]
Could you run `make docs`, and rename your title according to our conventions?

**Comment by frederikdesmedt** [comment]
Hey Allison, should be good now

**Comment by sfc-gh-swinkler** [comment]
@frederikdesmedt thank you for your contribution! 😄

**Pull request merged**
