### PR TITLE
fix: Deleting a snowflake_user and their associated snowlfake_role_grant causes an error

### LINKED ISSUE #889: Deleting a snowflake_user and their associated snowlfake_role_grant causes an error
**Provider Version**

```
$ terraform version
Terraform v0.14.11
+ provider registry.terraform.io/aidanmelen/snowsql v0.2.1
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.36
```

**Describe the bug**

When you delete a snowflake_user and their associated snowflake_role_grant, you'll get an error. The user and the grant are both deleted successfully, but you still get an error.

**Expected behavior**

The user and the role grant should be deleted without an error.

**Code samples and commands**

```
locals {
  staff = [
    "aperson",
    "bperson",
    "cperson",
  ]
}

resource "snowflake_role" "humans" {
  name    = "HUMANS"
  comment = "A role."
}

resource "snowflake_user" "humans" {
  for_each             = toset(local.staff)
  name                 = upper(each.key)
  login_name           = "${each.key}@example.com"
  disabled             = false
  display_name         = upper(each.key)
  email                = "${each.key}@example.com"
  password             = null
  default_role         = snowflake_role.humans.name
  must_change_password = false
}

resource "snowflake_role_grants" "grants" {
  role_name  = snowflake_role.humans.name
  users      = [for user in local.staff : upper(user)]
  depends_on = [snowflake_user.humans]
}
```

**Additional context**

1. Apply the above infrastructure which will create a role, three users, and it will grant three users access to the role.
2. Delete `bperson` from the staff list.
3. Run an `plan` and Terraform will propose that it's going to drop the user and their role grant, as expected.
```
  # snowflake_role_grants.grants will be updated in-place
  ~ resource "snowflake_role_grants" "grants" {
        id        = "HUMANS"
      ~ users     = [
          - "BPERSON",
            # (2 unchanged elements hidden)
        ]
        # (2 unchanged attributes hidden)
    }

  # snowflake_user.humans["bperson"] will be destroyed
  - resource "snowflake_user" "humans" {
      - default_role         = "HUMANS" -> null
      - disabled             = false -> null
      - display_name         = "BPERSON" -> null
      - email                = "bperson@example.com" -> null
      - has_rsa_public_key   = false -> null
      - id                   = "BPERSON" -> null
      - login_name           = "BPERSON@EXAMPLE.COM" -> null
      - must_change_password = false -> null
      - name                 = "BPERSON" -> null
    }

Plan: 0 to add, 1 to change, 1 to destroy.
```

4. Run an `apply` and you'll get this error:
```
Error: 002003 (02000): SQL compilation error:
User 'BPERSON' does not exist or not authorized.

  on test.tf line 26, in resource "snowflake_role_grants" "grants":
  26: resource "snowflake_role_grants" "grants" {
```
5. The user and their grant are both deleted as expected, so you shouldn't get any error.

### PR DESCRIPTION
**Pull request by mwiewior**
This is to fix #889 by checking a Snowflake SQL error code and printing a warning instead of failing in case of non-existing user.

## Test Plan

* [ x] acceptance tests

* [ ] …

## References

*

### CODE REVIEW

**Comment by mwiewior** [comment]
Hi @sfc-gh-jalin maybe you could take a look as well - this is sth that really makes it hard to manage users/roles from Terraform and already a few persons have upvoted this issue as well. Thx!

**Comment by sfc-gh-jlove** [comment]
Hi @mwiewior

We plan to take a look at this but we currently have very low bandwidth on the team.

**Comment by mwiewior** [comment]
ok, thx - just ping me if can help you somehow

**Comment by mwiewior** [comment]
@sfc-gh-jlove hey any chance you will have some time for this one ?

**Comment by sfc-gh-swinkler** [comment]
@mwiewior sorry i was on grievance leave. my wife died last month and there wasn't anyone else on the team who could approve PRs. i am catching up now.

**Review by sfc-gh-swinkler — APPROVED** [review]

**Comment by sfc-gh-swinkler** [comment]
thank you for your contribution

**Pull request merged**
