### PR TITLE
feat: add column masking policy specification

### PR DESCRIPTION
**Pull request by brewerdaniel-IW**
## Test Plan
* Existing tests have been augmented to check the creation of tables with a masking policy applied to a column
* Manual testing of: Creating a table with a column with a masking policy then removing that masking policy, creating a table with a column with no masking policy then adding a masking policy

## Issue
This PR is to solve [this issue](https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/303).

### CODE REVIEW

**Comment by alldoami** [comment]
Could you add an integration test as well? https://github.com/chanzuckerberg/terraform-provider-snowflake/blob/main/pkg/resources/table_acceptance_test.go

**Comment by gpamidimukkala** [comment]
Hi,
Is this patch completed and merged to main? How do I use this feature? Can you please share the details? The current terraform details that I am using are as below
Terraform v1.1.4
on darwin_amd64
+ provider registry.terraform.io/chanzuckerberg/snowflake v0.25.34

**Comment by brewerdaniel-IW** [comment]
Due to the way that masking policies work in Snowflake adding integration tests is a bit tricky! I've not had any time to really work on it in the last month but I hope to get around to it eventually!

**Comment by gpamidimukkala** [comment]
> Due to the way that masking policies work in Snowflake adding integration tests is a bit tricky! I've not had any time to really work on it in the last month but I hope to get around to it eventually!

Thanks for getting back Daniel. So Terraform is not an option for using masking policy?. Even I create a policy and assign it to a column in snowflake UI (using alter table) , next time when I execute terraform I get an error 

error deleting masking policy FIRST_NAME_MASK: 003531 (23001): SQL compilation error: Policy FIRST_NAME_MASK cannot be dropped/replaced as it is associated with one or more entities.


Thanks

**Comment by internetofjames** [comment]
@gpamidimukkala snowflake is a little tricky with masking policies. If you with to recreate a masking policy while it is assigned to one or more columns, you must drop all the associations, recreate the masking policy, and then re-apply the policies to the columns again.

There are options to modify the masking policy via alter statements, but this is limited to changing the name, changing the masking policy body, or changing the comment.

**Comment by gpamidimukkala** [comment]
> @gpamidimukkala snowflake is a little tricky with masking policies. If you with to recreate a masking policy while it is assigned to one or more columns, you must drop all the associations, recreate the masking policy, and then re-apply the policies to the columns again.
> 
> There are options to modify the masking policy via alter statements, but this is limited to changing the name, changing the masking policy body, or changing the comment.

So the only way to apply dynamic data masking at this moment is to do it directly in snowflake using scripts not through terraform?

**Comment by internetofjames** [comment]
@gpamidimukkala to be honest, I don't entirely know as I'm having [this separate issue](https://github.com/chanzuckerberg/terraform-provider-snowflake/issues/884) with masking policies that's preventing me from even creating them 🤷‍♂️

**Comment by nafarlee** [comment]
@brewerdaniel-IW I don't mean to impose (and please tell me if I am), but if you do not currently have capacity for this PR (and won't in the near future), would you be opposed to me continuing it? I would hate for what is here so far to go to waste.

**Comment by rparavia-encora** [comment]
Hoping this feature gets tested and released soon. Applying masking policies is critical functionality for my current team.

**Comment by jackmccabes** [comment]
@brewerdaniel-IW Would I be ok to add the necessary integration tests to get this merged.
This is a pretty essential Snowflake feature so would really like to get it merged.

**Comment by sfc-gh-swinkler** [comment]
this is only failing on the check-docs step. i will go ahead and merge this and run `make docs` myself. @jackmccabes if you are able to create a follow up PR to add integration tests, i would appreciate that.

**Pull request merged**
