### PR TITLE
feat: Adding users datasource

### PR DESCRIPTION
**Pull request by FrancisLfg**
Adds new datasource for users with pattern for filtering.

## Test Plan

* [x] acceptance tests (ran on trial account)

Please feel free to comment or suggest any modifications.

### CODE REVIEW

**Review by sfc-gh-jalin — APPROVED** [review]

**Comment by FrancisLfg** [comment]
Hello @sfc-gh-jalin, ok no problem, I just pushed the docs, lets wait for the check-docs step.

**Pull request merged**
