### PR TITLE
Update index.md to include authenticator config value

### PR DESCRIPTION
**Pull request by Zesky665**
Added authenticator value to the documentation. 

## Test Plan

* [ ] acceptance tests

* [ ] …

## References

*

### CODE REVIEW

**Comment by sfc-gh-asawicki** [comment]
Hey @Zesky665. Thanks for the suggestion.

This change cannot be merged, though. The reason is, that the docs (markdown files) are generated. You have to change the input (`examples/provider/provider.tf`) and then regenerate the docs. Without such a change it will be lost with the next docs generation. To generate them, you would have to:
1. update the example
2. setup dev env (`make dev-setup`)
3. generate the docs (`make pre-push`).

I am just writing this as an explanation for the future. I will introduce such change today with one of my other PRs.

We do not have proper contribution guidelines yet, but this is something we will introduce in the next couple of weeks. Docs generation will be one of the topics described there.

**Comment by Zesky665** [comment]
@sfc-gh-asawicki Thank you for the heads up. 

Please let me know when the contribution guidelines are introduced, I would very much like to work on improving the documentation.

**Comment by sfc-gh-asawicki** [comment]
Superseded by #2515

**Comment by sfc-gh-asawicki** [comment]
Hey @Zesky665 . We have refreshed the contribution guidelines: https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/CONTRIBUTING.md. Please let me know if you think anything is missing.

**Pull request closed without merging**
