### PR TITLE
fix: Add missing Google Cloud computed property api_gcp_service_accou…

### LINKED ISSUE #1775: snowflake_api_integration does not provide read-only api_gcp_service_account property
**Provider Version**

0.63.0

**Terraform Version**

1.4.2

**Describe the bug**

Resource snowflake_api_integration does not expose `api_gcp_service_account`property as an output variable.

**Expected behavior**

snowflake_api_integration should expose service account name for GCP that can be used for IAM configuration.

### PR DESCRIPTION
**Pull request by mwiewior**
Fixes #1775 

Tests:
```bash
(base) ➜  terraform-provider-snowflake git:(issue-1775) ✗ go test github.com/Snowflake-Labs/terraform-provider-snowflake/pkg/resources -run "^TestAcc_ApiIntegration$" -v
=== RUN   TestAcc_ApiIntegration
--- PASS: TestAcc_ApiIntegration (7.64s)
PASS

```

### CODE REVIEW

**Comment by mwiewior** [comment]
hey @sfc-gh-swinkler - any chance to get this minor things reviewed and merged, it would be very helpful for our GCP integrations...

**Comment by mwiewior** [comment]
hey @sfc-gh-ngaberel could you please take a look at this minor one?

**Review by sfc-gh-swinkler — APPROVED** [review]
LGTM!

**Comment by sfc-gh-swinkler** [comment]
@mwiewior thank you for your contribution!

**Pull request merged**
