### PR TITLE
docs: typo on README

### PR DESCRIPTION
**Pull request by senmm**
Fix a small typo.

### CODE REVIEW

**Comment by sfc-gh-swinkler** [comment]
can you please run `make check-docs` ?

**Comment by senmm** [comment]
@sfc-gh-swinkler Thank you for your message. I ran `make check-docs` and I found some files to need to fix. Could you please recheck this PR?

**Review by sfc-gh-swinkler — APPROVED** [review]
LGTM

**Comment by sfc-gh-swinkler** [comment]
thank you for your contribution

**Pull request merged**
