### PR TITLE
fix: dont set query_acceleration_max_scale_factor when not enabled

### PR DESCRIPTION
**Pull request by mnagaa**
One of my snowflake accounts is using the Standard edition.
Recently, a functionality for query acceleration as the warehouse parameter has been implemented in Snowflake.

For standard editions, the warehouse parameter `enable_query_acceleration` is always set to false because this acceleration can be used for Enterprise edition users. 

The following queries are invalid for  Standard user and raises error like attached image of snowflake console.
`alter warehouse WAREHOUSE_NAME set query_acceleration_max_scale_factor = 0;`
`alter warehouse WAREHOUSE_NAME set query_acceleration_max_scale_factor = 8;`

As a workaround for this, I change lines to alter `query_acceleration_max_scale_factor` only if enable_query_acceleration is true.

I am not sure the implementation around this functionality, please review carefully.

### CODE REVIEW

**Comment by mnagaa** [comment]
Related to #1343

**Comment by sfc-gh-swinkler** [comment]
This seems like a reasonable solution. If you can't read the value with Standard edition, then don't bother even trying.

**Review by sfc-gh-swinkler — APPROVED** [review]

**Comment by belacevic** [comment]
This, unfortunately doesn't seem to have helped with creating new warehouses, as Terraform still adds the default value `8` to the (non supported) attribute, even when setting:

```
enable_query_acceleration = false
```

and 

```
  lifecycle {
    ignore_changes = [
      query_acceleration_max_scale_factor
    ]
  }
```

**Comment by forest** [comment]
Duplicate: https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/1944

**Pull request merged**
