### PR TITLE
fix: Remove validate_utf8 parameter from file_format

### PR DESCRIPTION
**Pull request by gary-beautypie**
Remove validate_utf8 parameter from file_format due to obsoletion from Snowflake

## Test Plan
* [x] acceptance tests

## References

* #1147

### CODE REVIEW

**Comment by sfc-gh-jalin** [comment]
For reference: https://community.snowflake.com/s/article/VALIDATE-UTF8-File-Format-Option-Obsoleted

**Comment by gary-beautypie** [comment]
not sure those errors are to do with the commit? 😬

**Comment by sfc-gh-jalin** [comment]
> not sure those errors are to do with the commit? 😬

Apologies, I entered the wrong commit ID. Rerunning the tests now

**Review by sfc-gh-jalin — APPROVED** [review]

**Pull request merged**
