### PR TITLE
feat: Add Manage Warehouses Account Grant

### PR DESCRIPTION
**Pull request by GtheSheep**
Add [MANAGE WAREHOUSES](https://docs.snowflake.com/en/user-guide/warehouses-tasks#label-grant-manage-warehouses-privilege) account privilege

## Test Plan
* [x] acceptance tests

## References
[Snowflake Docs](https://docs.snowflake.com/en/user-guide/warehouses-tasks#label-grant-manage-warehouses-privilege)

### CODE REVIEW

**Comment by NiallRees** [comment]
Hey @scottwinkler - any chance we can get this merged? ty!

**Comment by NiallRees** [comment]
Hi @sfc-gh-asawicki, @sfc-gh-pbosak - should be an easy approval to get into the next release? 🙏

**Comment by ian-whitestone** [comment]
Hey folks, any chance we merge this? A bunch of Snowflake users are asking for this

**Comment by sfc-gh-asawicki** [comment]
LGTM.

@GtheSheep, can you please rebase on the newest main so that we can run integration tests?

**Comment by GtheSheep** [comment]
@sfc-gh-asawicki - updated!

**Comment by GtheSheep** [comment]
@sfc-gh-asawicki - Errors don't seem related to this change? PipeGrants/ PwdPolicy

**Comment by sfc-gh-asawicki** [comment]
@GtheSheep, yeah, we will be working on the stability of the tests shortly because, sadly, there are plenty of flaky ones... Let me retry them.

**Review by sfc-gh-asawicki — APPROVED** [review]

**Review by sfc-gh-jcieslak — APPROVED** [review]

**Comment by sfc-gh-asawicki** [comment]
@GtheSheep merged; thanks for your contribution!

**Pull request merged**
