### PR TITLE
feat: Add allowed values

### PR DESCRIPTION
**Pull request by sfc-gh-kmaurya**
Replaced GetChange() method with Get() in the update function of tag
## Test Plan

* [ ] acceptance tests

* [ ] …

## References

*

### CODE REVIEW

**Comment by alldoami** [comment]
@sfc-gh-kmaurya could you more accurately describe what you're doing in the PR title?

**Comment by scottwinkler** [comment]
@sfc-gh-kmaurya looking at the code commit it appears both of these changes will have no effect and have nothing to do with allowed_values. when you rebased the code to main did you accidentally lose your commits?

**Review by sfc-gh-swinkler — APPROVED** [review]
minor change, doesn't affect anything

**Pull request merged**
