### PR TITLE
feat: Adding warehouse type for snowpark optimized warehouses

### PR DESCRIPTION
**Pull request by astanfel**
## Summary of changes

* Added warehouse type for snowpark optimized warehouses

* Updated Docs

* Update warehouse.go

## References
* [snowpark-optimized-warehouses](https://docs.snowflake.com/en/user-guide/warehouses-snowpark-optimized.html#snowpark-optimized-warehouses)

### CODE REVIEW

**Comment by git-benjamin** [comment]
Hi all is there any progress on this?

**Comment by astanfel** [comment]
@sfc-gh-swinkler could you run that test again? I fixed the syntax issue that was reported

**Comment by sfc-gh-swinkler** [comment]
@astanfel one last thing - could you please run the command `make docs`?

**Comment by astanfel** [comment]
```bash 
make docs                                                                                                                                                                                                                                                                                                   ──(Wed,Dec07)─┘
SNOWFLAKE_USER= SNOWFLAKE_ACCOUNT= go run github.com/hashicorp/terraform-plugin-docs/cmd/tfplugindocs
rendering website for provider "terraform-provider-snowflake" (as "terraform-provider-snowflake")
copying any existing content to tmp dir
exporting schema from Terraform
compiling provider "snowflake"
using Terraform CLI binary from PATH if available, otherwise downloading latest Terraform CLI binary
running terraform init
getting provider schema
rendering missing docs
generating missing resource content
generating template for "snowflake_sequence"
generating template for "snowflake_user_ownership_grant"
generating template for "snowflake_external_function"
generating template for "snowflake_function"
generating template for "snowflake_role_grants"
generating template for "snowflake_role_ownership_grant"
generating template for "snowflake_user_public_keys"
generating template for "snowflake_view_grant"
generating template for "snowflake_schema_grant"
generating template for "snowflake_view"
generating template for "snowflake_external_oauth_integration"
generating template for "snowflake_task_grant"
generating template for "snowflake_warehouse_grant"
generating template for "snowflake_stage_grant"
generating template for "snowflake_tag_association"
generating template for "snowflake_resource_monitor"
generating template for "snowflake_row_access_policy"
generating template for "snowflake_share"
generating template for "snowflake_storage_integration"
generating template for "snowflake_table_grant"
generating template for "snowflake_function_grant"
generating template for "snowflake_materialized_view_grant"
generating template for "snowflake_schema"
generating template for "snowflake_stream"
generating template for "snowflake_stream_grant"
generating template for "snowflake_procedure"
generating template for "snowflake_role"
generating template for "snowflake_sequence_grant"
generating template for "snowflake_tag_masking_policy_association"
generating template for "snowflake_warehouse"
generating template for "snowflake_procedure_grant"
generating template for "snowflake_user"
generating template for "snowflake_integration_grant"
generating template for "snowflake_masking_policy"
generating template for "snowflake_pipe_grant"
generating template for "snowflake_masking_policy_grant"
generating template for "snowflake_network_policy_attachment"
generating template for "snowflake_api_integration"
generating template for "snowflake_external_table_grant"
generating template for "snowflake_file_format"
generating template for "snowflake_stage"
generating template for "snowflake_table"
generating template for "snowflake_external_table"
generating template for "snowflake_file_format_grant"
generating template for "snowflake_notification_integration"
generating template for "snowflake_managed_account"
generating template for "snowflake_network_policy"
generating template for "snowflake_scim_integration"
generating template for "snowflake_account_grant"
generating template for "snowflake_database_grant"
generating template for "snowflake_failover_group"
generating template for "snowflake_saml_integration"
generating template for "snowflake_tag_grant"
generating template for "snowflake_task"
generating template for "snowflake_user_grant"
generating template for "snowflake_database"
generating template for "snowflake_oauth_integration"
generating template for "snowflake_row_access_policy_grant"
generating template for "snowflake_table_constraint"
generating template for "snowflake_tag"
generating template for "snowflake_materialized_view"
generating template for "snowflake_pipe"
generating template for "snowflake_resource_monitor_grant"
generating missing data source content
generating template for "snowflake_file_formats"
generating template for "snowflake_role"
generating template for "snowflake_system_get_privatelink_config"
generating template for "snowflake_resource_monitors"
generating template for "snowflake_roles"
generating template for "snowflake_row_access_policies"
generating template for "snowflake_pipes"
generating template for "snowflake_system_generate_scim_access_token"
generating template for "snowflake_system_get_snowflake_platform_info"
generating template for "snowflake_warehouses"
generating template for "snowflake_system_get_aws_sns_iam_policy"
generating template for "snowflake_current_account"
generating template for "snowflake_external_tables"
generating template for "snowflake_materialized_views"
generating template for "snowflake_storage_integrations"
generating template for "snowflake_database"
generating template for "snowflake_functions"
generating template for "snowflake_sequences"
generating template for "snowflake_tasks"
generating template for "snowflake_databases"
generating template for "snowflake_stages"
generating template for "snowflake_streams"
generating template for "snowflake_views"
generating template for "snowflake_tables"
generating template for "snowflake_users"
generating template for "snowflake_external_functions"
generating template for "snowflake_masking_policies"
generating template for "snowflake_procedures"
generating template for "snowflake_schemas"
generating missing provider content
provider "terraform-provider-snowflake" template exists, skipping
rendering static website
cleaning rendered website dir
rendering templated website to static markdown
rendering "data-sources/current_account.md.tmpl"
rendering "data-sources/database.md.tmpl"
rendering "data-sources/databases.md.tmpl"
rendering "data-sources/external_functions.md.tmpl"
rendering "data-sources/external_tables.md.tmpl"
rendering "data-sources/file_formats.md.tmpl"
rendering "data-sources/functions.md.tmpl"
rendering "data-sources/masking_policies.md.tmpl"
rendering "data-sources/materialized_views.md.tmpl"
rendering "data-sources/pipes.md.tmpl"
rendering "data-sources/procedures.md.tmpl"
rendering "data-sources/resource_monitors.md.tmpl"
rendering "data-sources/role.md.tmpl"
rendering "data-sources/roles.md.tmpl"
rendering "data-sources/row_access_policies.md.tmpl"
rendering "data-sources/schemas.md.tmpl"
rendering "data-sources/sequences.md.tmpl"
rendering "data-sources/stages.md.tmpl"
rendering "data-sources/storage_integrations.md.tmpl"
rendering "data-sources/streams.md.tmpl"
rendering "data-sources/system_generate_scim_access_token.md.tmpl"
rendering "data-sources/system_get_aws_sns_iam_policy.md.tmpl"
rendering "data-sources/system_get_privatelink_config.md.tmpl"
rendering "data-sources/system_get_snowflake_platform_info.md.tmpl"
rendering "data-sources/tables.md.tmpl"
rendering "data-sources/tasks.md.tmpl"
rendering "data-sources/users.md.tmpl"
rendering "data-sources/views.md.tmpl"
rendering "data-sources/warehouses.md.tmpl"
rendering "index.md.tmpl"
rendering "resources/account_grant.md.tmpl"
rendering "resources/api_integration.md.tmpl"
rendering "resources/database.md.tmpl"
rendering "resources/database_grant.md.tmpl"
rendering "resources/external_function.md.tmpl"
rendering "resources/external_oauth_integration.md.tmpl"
rendering "resources/external_table.md.tmpl"
rendering "resources/external_table_grant.md.tmpl"
rendering "resources/failover_group.md.tmpl"
rendering "resources/file_format.md.tmpl"
rendering "resources/file_format_grant.md.tmpl"
rendering "resources/function.md.tmpl"
rendering "resources/function_grant.md.tmpl"
rendering "resources/integration_grant.md.tmpl"
rendering "resources/managed_account.md.tmpl"
rendering "resources/masking_policy.md.tmpl"
rendering "resources/masking_policy_grant.md.tmpl"
rendering "resources/materialized_view.md.tmpl"
rendering "resources/materialized_view_grant.md.tmpl"
rendering "resources/network_policy.md.tmpl"
rendering "resources/network_policy_attachment.md.tmpl"
rendering "resources/notification_integration.md.tmpl"
rendering "resources/oauth_integration.md.tmpl"
rendering "resources/pipe.md.tmpl"
rendering "resources/pipe_grant.md.tmpl"
rendering "resources/procedure.md.tmpl"
rendering "resources/procedure_grant.md.tmpl"
rendering "resources/resource_monitor.md.tmpl"
rendering "resources/resource_monitor_grant.md.tmpl"
rendering "resources/role.md.tmpl"
rendering "resources/role_grants.md.tmpl"
rendering "resources/role_ownership_grant.md.tmpl"
rendering "resources/row_access_policy.md.tmpl"
rendering "resources/row_access_policy_grant.md.tmpl"
rendering "resources/saml_integration.md.tmpl"
rendering "resources/schema.md.tmpl"
rendering "resources/schema_grant.md.tmpl"
rendering "resources/scim_integration.md.tmpl"
rendering "resources/sequence.md.tmpl"
rendering "resources/sequence_grant.md.tmpl"
rendering "resources/share.md.tmpl"
rendering "resources/stage.md.tmpl"
rendering "resources/stage_grant.md.tmpl"
rendering "resources/storage_integration.md.tmpl"
rendering "resources/stream.md.tmpl"
rendering "resources/stream_grant.md.tmpl"
rendering "resources/table.md.tmpl"
rendering "resources/table_constraint.md.tmpl"
rendering "resources/table_grant.md.tmpl"
rendering "resources/tag.md.tmpl"
rendering "resources/tag_association.md.tmpl"
rendering "resources/tag_grant.md.tmpl"
rendering "resources/tag_masking_policy_association.md.tmpl"
rendering "resources/task.md.tmpl"
rendering "resources/task_grant.md.tmpl"
rendering "resources/user.md.tmpl"
rendering "resources/user_grant.md.tmpl"
rendering "resources/user_ownership_grant.md.tmpl"
rendering "resources/user_public_keys.md.tmpl"
rendering "resources/view.md.tmpl"
rendering "resources/view_grant.md.tmpl"
rendering "resources/warehouse.md.tmpl"
rendering "resources/warehouse_grant.md.tmpl"
```

**Comment by astanfel** [comment]
@sfc-gh-swinkler Added another commit after running make docs

**Review by sfc-gh-swinkler — APPROVED** [review]

**Pull request merged**
