### PR TITLE
feat: Data sources for replication databases and accounts, and organization accounts

### PR DESCRIPTION
**Pull request by mlorek**
## Test Plan

* [x] acceptance tests

* [x] …

## References

* https://docs.snowflake.com/en/sql-reference/sql/show-replication-accounts.html
* https://docs.snowflake.com/en/sql-reference/sql/show-replication-databases.html

### CODE REVIEW

**Comment by alldoami** [comment]
Could you attach reference docs on these data sources?

**Comment by mlorek** [comment]
> Could you attach reference docs on these data sources?

any particular place these docs should be added to?

**Comment by alldoami** [comment]
@mlorek just to the description of the PR!

Could you also run `make docs`?

**Comment by mlorek** [comment]
> @mlorek just to the description of the PR!
> 
> Could you also run `make docs`?

done

**Comment by mlorek** [comment]
> /ok-to-test sha=899983e

anything I can do to help?

**Comment by alldoami** [comment]
You can find the test failures if you click on the failed test link in that comment. Looks like you need to assign the ID to the data sources.

**Comment by mlorek** [comment]
> You can find the test failures if you click on the failed test link in that comment. Looks like you need to assign the ID to the data sources.

`show organization accounts` will fail unless the orgadmin role is used.

**Pull request closed without merging**
