### PR TITLE
feat: addition of the on_all option for all remaining resources

### PR DESCRIPTION
**Pull request by Relativity74205**
Add on_all option for
- external tables
- file_formats
- functions
- procedures
- sequences
- streams
- tasks

## Test Plan
* [x] acceptance tests
* [x] unit tests

## References
https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1626
https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1686
https://github.com/Snowflake-Labs/terraform-provider-snowflake/pull/1713

### CODE REVIEW

**Comment by Relativity74205** [comment]
@sfc-gh-swinkler The on_all feature should be now completed with this MR.

**Comment by jgogstad** [comment]
@Relativity74205 mark PR as ready for review?

Thank you for these contributions!

**Comment by Relativity74205** [comment]
> @Relativity74205 mark PR as ready for review?
> 
> Thank you for these contributions!

Done. Sorry, forgot this.

**Comment by sfc-gh-swinkler** [comment]
@Relativity74205 sorry it took me a while to get to this. It looks great, thanks! 

Also, since you are an active contributor, I would like to let you know that I have been working on a new structure for the  SDK, see: https://github.com/Snowflake-Labs/terraform-provider-snowflake/discussions/1767.

**Review by sfc-gh-swinkler — APPROVED** [review]

**Pull request merged**
