### PR TITLE
docs: Fix pipe_grant doc

### PR DESCRIPTION
**Pull request by yohei1126**
* https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/pipe_grant
* This PR fix https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/985
* current `pipe_grant` document contains `sequence_name = "sequence"` but it must be like `pipe_name = "pipe"

## Test Plan

* [x] acceptance tests

* [ ] …

## References

* https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/985

### CODE REVIEW

**Comment by yohei1126** [comment]
@sfc-gh-swinkler done

**Comment by yohei1126** [comment]
@sfc-gh-swinkler would you check this PR?

**Review by sfc-gh-swinkler — APPROVED** [review]

**Comment by yohei1126** [comment]
@sfc-gh-swinkler done

**Comment by sfc-gh-jalin** [comment]
Sorry @yohei1126, could you rebase one more time? I was working on some other changes and merged them in before checking back on this PR

**Comment by yohei1126** [comment]
done

**Pull request merged**
