### PR TITLE
fix: oauth integration

### LINKED ISSUE #785: Support Custom OAuth Integration Type
**Is your feature request related to a problem? Please describe.**

I need to support a custom OAuth security integration for Retool

**Describe the solution you'd like**

Ability to specify "CUSTOM" with `oauth_client_type` and `oauth_redirect_uri` parameters when defining a `snowflake_oauth_integration` resource.

**Describe alternatives you've considered**

Manually managing this or using password-based auth for this connection.

**Additional context**

Recently it looks like the `snowflake_oauth_integration` resource was added (https://github.com/chanzuckerberg/terraform-provider-snowflake/pull/763). Which is great. It doesn't support `CUSTOM` OAuth types though, which requires only a couple additional (optional) properties: https://docs.snowflake.com/en/sql-reference/sql/create-security-integration.html#snowflake-oauth-custom-client-parameters

I need this to support an OAuth connection for Retool, which only has password or custom OAuth connection options.

### PR DESCRIPTION
**Pull request by kevinneville**
Resolves #785 

When using https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/oauth_integration with a custom client we need two required arguments. [oauth_redirect_uri](https://registry.terraform.io/providers/Snowflake-Labs/snowflake/latest/docs/resources/oauth_integration#oauth_redirect_uri) and oauth_client type. Today only `oauth_redirect_uri` is supported.

This PR aims to solve that.

When I use
```
resource "snowflake_oauth_integration" "new_integration" {
  provider           = snowflake.SYSADMIN
  name               = "NEW_INTEGRATION"
  oauth_client       = "CUSTOM"
  enabled            = true
  oauth_redirect_uri = "MY_URL"
}
```
I get the following error.
```
│ Error: error creating security integration: 002029 (42601): SQL compilation error:
│ Missing option(s): OAUTH_CLIENT_TYPE
```
When using below Terraform code
```
resource "snowflake_oauth_integration" "new_integration" {
  provider           = snowflake.SYSADMIN
  name               = "NEW_INTEGRATION"
  oauth_client_type  = "CONFIDENTIAL"
  oauth_client       = "CUSTOM"
  enabled            = true
  oauth_redirect_uri = "MY_URL"
}
```
I get
```
│ An argument named "oauth_client_type" is not expected here.
```

## References
See https://docs.snowflake.com/en/sql-reference/sql/create-security-integration-oauth-snowflake.html#additional-required-parameters-custom-clients to prove this is needed.

### CODE REVIEW

**Comment by kevinneville** [comment]
@sfc-gh-swinkler
Hello,
I noticed you worked on the redirect URI, and I tried to follow your steps. Could you review it?
I also think it would be good to add a test for this. But I am unsure how and where to do it, could you assist with this PR?

My gut feeling says somewhere here https://github.com/Snowflake-Labs/terraform-provider-snowflake/blob/main/pkg/provider/provider_test.go#L109 but not sure.

Any advice would be appreciated.

**Review by sfc-gh-swinkler — DISMISSED** [review]

**Comment by kevinneville** [comment]
@sfc-gh-swinkler Since I am a first-time contributor I can't trigger the builds, would you mind? Then we can merge it.

**Comment by sfc-gh-swinkler** [comment]
@kevinneville sorry for the past few days have been having trouble getting the latest release out so was not able to merge PRs.  This is failing a couple of minor checks:
1. `go fmt ./...` needs to be run
2. `make docs` needs to be run

After those both pass i can run unit / integration tests and get this merged. Thanks!

**Comment by kevinneville** [comment]
> @kevinneville sorry for the past few days have been having trouble getting the latest release out so was not able to merge PRs. This is failing a couple of minor checks:
> 
> 1. `go fmt ./...` needs to be run
> 2. `make docs` needs to be run
> 
> After those both pass i can run unit / integration tests and get this merged. Thanks!

Alright, let me know if I can assist in any way.
I updated the code and those checks should pass now.

**Comment by sfc-gh-swinkler** [comment]
```
== CONT  TestAcc_OAuthIntegration
    oauth_integration_acceptance_test.go:16: Step 1/2 error: Error running apply: exit status 1
        
        Error: error creating security integration: 001420 (22023): SQL compilation error:
        invalid property 'OAUTH_CLIENT_TYPE' for 'INTEGRATION - OAUTH - TABLEAU_SERVER'
        
          on terraform_plugin_test.tf line 3, in resource "snowflake_oauth_integration" "test":
           3: 	resource "snowflake_oauth_integration" "test" {
        
        
--- FAIL: TestAcc_OAuthIntegration (2.15s)
```

@kevinneville so the value being returned by `if err = d.Set("oauth_client_type", v.(string)); err != nil {` is not what you think it is. It looks like the value is  'INTEGRATION - OAUTH - TABLEAU_SERVER'. I am not familiar with this. Can "confidential" or "public" be inferred from this value or does it need to be queried from some other API endpoint?

**Comment by culpgrant** [comment]
Do we think there would be any possibility this could get merged in? I see there is still one remaining issue.
I am trying to set up DBT Cloud and this is required but currently, the resource doesn't work for the issue in this PR  :)

**Pull request merged**
