### PR TITLE
feat: add GRANT ... ON ALL TABLES IN ...

### PR DESCRIPTION
**Pull request by Relativity74205**
In an number of issues, the snowflake feature GRANT SELECT ON **_ALL_** TABLES ... (or similar) is requested. I created a prototype of this feature in this branch. Currently it only works for the table resource (not for others).

Before I finish this work (add unit and acceptance tests, implement it on other resources, etc.) I would like to have an opinion if this feature makes sense. Not only how it was implemented, but also generally. Because:

When running e.g. GRANT SELECT ON ALL TABLES IN ..., then Snowflake creates a grant for each individual existing table and there is no way to attribute existing table grants to a GRANT SELECT ON ALL TABLES grant. Thus they cannot be checked (or removed).

## Test Plan
tbd

* [ ] acceptance tests

* [ ] …

## References
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/787
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/250
https://github.com/Snowflake-Labs/terraform-provider-snowflake/issues/284

### CODE REVIEW

**Comment by sfc-gh-swinkler** [comment]
@Relativity74205 this is very good. I like this a lot. I think i will merge this, get the tests working, and it should be good to go.

**Comment by Relativity74205** [comment]
@sfc-gh-swinkler Thanks for the review and acceptance. :)

**Comment by sfc-gh-swinkler** [comment]
@Relativity74205 your code was pretty good as it was, and i didn't have to make too many changes. Its currently released as part of 0.60. Thank you so much!

**Comment by TerjeRusska** [comment]
@Relativity74205 Awesome feature, I've been looking for this for quite a few months :smile: Dropped my resource count from table level 4096 to schema level 106 :tada:

**Pull request merged**
