### PR TITLE
feat: Streams on views

### PR DESCRIPTION
**Pull request by gouline**
Allow streams on views (rather than tables), now that it's in public preview.

## Test Plan

* [x] acceptance tests

## References

* [CREATE STREAM](https://docs.snowflake.com/en/sql-reference/sql/create-stream.html)

### CODE REVIEW

**Comment by sfc-gh-jalin** [comment]
Hi @gouline, can you rebase please? And you can ignore the failing slack-notifications step, we are currently working on that as a side project

**Comment by gouline** [comment]
Looks like something's up with CI 🤨 

```
make: *** No rule to make target 'test-acceptance'.  Stop.
```

**Comment by sfc-gh-jalin** [comment]
> Looks like something's up with CI 🤨
> 
> ```
> make: *** No rule to make target 'test-acceptance'.  Stop.
> ```

Think I got the wrong commit ID, it's running [now](https://github.com/Snowflake-Labs/terraform-provider-snowflake/runs/7332091756?check_suite_focus=true)

**Comment by gouline** [comment]
Sorry, that was my bad - I initially just merged the main branch in (fab210e) and then did a rebase like you asked (40568af). Looks good now.

**Pull request merged**
