### PR TITLE
feat: Adding support for debugger-based debugging.

### PR DESCRIPTION
**Pull request by sandor-juhasz**
Fix for Snowflake-Labs#1144

Adding the `-debug` flag to enable starting the provider in debug mode according to https://www.terraform.io/plugin/debugging#debugger-based-debugging

Specifying the `ProviderAddr` was required to let the provider print the proper command to set the `TF_REATTACH_PROVIDERS` environment variable once theprovider is started in debug mode. If not specified, the output will default to provider which will print a wrong command to the user. With this wrong command the debug session will not be established between the provider and the Terraform applicaiton.

## Test Plan
- Existing unit tests have been run.
- Manual testing has been performed with the following steps on Windows with VS Code
1. Launch the Snowflake Provider in VS Code debugger with the -debug argument. The process prints the following
```
Provider started. To attach Terraform CLI, set the TF_REATTACH_PROVIDERS environment variable with the following:

Command Prompt:	set "TF_REATTACH_PROVIDERS={"registry.terraform.io/Snowflake-Labs/snowflake":{"Protocol":"grpc","ProtocolVersion":5,"Pid":35140,"Test":true,"Addr":{"Network":"tcp","String":"127.0.0.1:54706"}}}"
PowerShell:	$env:TF_REATTACH_PROVIDERS='{"registry.terraform.io/Snowflake-Labs/snowflake":{"Protocol":"grpc","ProtocolVersion":5,"Pid":35140,"Test":true,"Addr":{"Network":"tcp","String":"127.0.0.1:54706"}}}'
```
2. In another command line window, execute the SET command printed in the previous step.
3. Execute any Terraform template exercising the Snowflake Terraform provider.
4. Verify that Terraform connects to the debug session by checking the outputted messages in the Debug Console in VS Code.
5. Place breakpoints in the code and check if the execution stops when execution reaches the breakpoint.

### CODE REVIEW

**Comment by sfc-gh-jalin** [comment]
Hi @sandor-juhasz this PR looks good to me but before merging, do you think it would be beneficial to add something to the readme about running the debugger? That way other people will be aware of this new feature and be able to use it

**Review by sfc-gh-jalin — APPROVED** [review]

**Comment by sandor-juhasz** [comment]
Hi @sfc-gh-jalin, that's good idea, I have added a couple of lines to the README.md and pushed it into my feature branch. Shall I squash it or clean up the branch in any other way? This is my first contribution and I'm still trying to get the hang of it.

**Pull request merged**
